spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/cogia
    username: cogia_prod
    password: tD9nj65aWYcd7<9}H
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest